# Generated by Django 2.0.5 on 2019-11-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='suscribers',
            new_name='subscribers',
        ),
    ]
