# Generated by Django 2.2.10 on 2020-06-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_auto_20200618_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel_subscription',
            old_name='Channel',
            new_name='channel',
        ),
    ]
